### ISSUE TITLE
images in question choices  

### ISSUE THREAD

**Issue by Cloneill-2021** [earthwiseaware/field_surveys#31]
In the setting media folder of the buggy project, I have added a few images. One is the logo of the app, which I have successfully added to the first page as a note. 

And then I added a set of images/icons for the survey method question (there are 5 pics, once for each choices). In the xlsform (attached here as well)
[EwA-Buggy-20220807-wLogo.xlsx](https://github.com/earthwiseaware/field_surveys/files/9277053/EwA-Buggy-20220807-wLogo.xlsx), you'll see in the choices tab, that I added them there as media::image. 
I followed: https://support.kobotoolbox.org/media.html#:~:text=of%20your%20XLSForm.-,Type%20the%20image%20file%20name%20along%20with%20an%20extension%20to,choices%20tab%20of%20your%20XLSForm.

 But in the later case, I am not successful. I am not sure what I am missing there.

**Comment by mgietzmann** [comment]
The appearance is set to w4 minimal, which is why nothing is displaying. I was able to see things after removing that specification.
 
<img width="1036" alt="Screen Shot 2022-08-08 at 10 02 13 PM" src="https://user-images.githubusercontent.com/16074833/183547340-9ee210e4-8fcd-4b1c-9b82-52a5b719a076.png">

**Comment by Cloneill-2021** [comment]
Wonderful! I'll get that in tomorrow then :-) Thanks!

**Comment by Cloneill-2021** [comment]
It worked for me...
